name: WarpsPro
main: nikoskon\WarpsPro\WarpsPro
author: nikoskon
version: 1.3.0
api: [3.0.0]
commands:
 warp:
  description: "Main warp command"
  usage: "/warp or /warp <warpname>"
  permission: warpspro.command.warp
 warps:
  description: "Main warp command"
  usage: "/warps or /warps <warpname>"
  permission: warpspro.command.warp
  
permissions:
 warpspro.*:
  default: op
  description: "Allows all warpspro commands"
  children:
     warpspro.command.delwarp:
      description: "Allows player to delete warps"
      default: op
     warpspro.command.setwarp:
      description: "Allows player to set warps"
      default: op
     warpspro.command.edit:
      description: "Allows player to edit warps"
      default: op
     warpspro.command.warp:
      description: "Allows player to use warps"
      default: true